"use strict";
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let index, manifest, selected = new Set(), stationMap;
const sourceMap = () => Object.fromEntries(index.sources.map(source => [source.id, source]));
const available = () => index.snapshots.filter(item => (!$("#date").value || item.date === $("#date").value) && (!$("#location").value || item.location.id === $("#location").value));
const option = (value, label) => `<option value="${esc(value)}">${esc(label)}</option>`;
function markdown(text) { return esc(text).replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h2>$1</h2>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/^[-*] (.+)$/gm,"<li>$1</li>").replace(/(?:<li>.*<\/li>\n?)+/g,x=>`<ul>${x}</ul>`).replace(/\n{2,}/g,"</p><p>").replace(/^/,"<p>").replace(/$/,"</p>"); }
async function json(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }
async function text(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.text(); }
function syncQuery() { const query = new URLSearchParams({date:$("#date").value, location:$("#location").value}); history.replaceState(null,"",`?${query}`); }
function initializeSelectors() { const query = new URLSearchParams(location.search); const dates = [...new Set(index.snapshots.map(x=>x.date))].sort().reverse(); $("#date").innerHTML = dates.map(x=>option(x,x)).join(""); $("#date").value = dates.includes(query.get("date")) ? query.get("date") : dates[0] || ""; updateLocations(query.get("location")); }
function updateLocations(preferred) { const items = index.snapshots.filter(x=>x.date === $("#date").value); $("#location").innerHTML = items.map(x=>option(x.location.id,`${x.location.prefecture} — ${x.location.city}`)).join(""); if (items.some(x=>x.location.id===preferred)) $("#location").value=preferred; }
async function loadSnapshot() { const item = available()[0]; if (!item) { $("#status").textContent="この組み合わせのsnapshotはありません。"; return; } syncQuery(); manifest=await json(item.manifest); selected=new Set(manifest.sources.map(x=>x.id)); renderFilters(); await render(); }
function renderFilters() { const defs=sourceMap(); $("#filters").innerHTML=manifest.sources.map(item=>`<label><input type="checkbox" value="${esc(item.id)}" ${selected.has(item.id)?"checked":""}><span><b>${esc(defs[item.id]?.name||item.name)}</b><small>${esc(defs[item.id]?.category||item.category)} · ${esc(item.status)}</small></span></label>`).join(""); }
async function loadData(entry) { return entry.data_path ? json(`${base()}/${entry.data_path}`) : null; }
function base() { return `snapshots/${manifest.target_date}/${manifest.location.id}`; }
async function render() { const visible=manifest.sources.filter(x=>selected.has(x.id)); $("#snapshot-title").textContent=`${manifest.target_date} · ${manifest.location.prefecture} ${manifest.location.city}`; $("#generated-at").textContent=`生成 ${manifest.generated_at||"—"}`; $("#status").textContent=`${visible.length} / ${manifest.sources.length} 資料を表示中`; $("#windy").href=`https://www.windy.com/${manifest.location.latitude}/${manifest.location.longitude}`;
  const failures=visible.filter(x=>!["success","cached"].includes(x.status)); $("#errors").innerHTML=failures.map(x=>`<div class="error"><b>${esc(x.name)}</b>：${esc(x.error?.message||x.status)}</div>`).join("");
  const groups={"地上":[],"高層":[],"数値予報":[],"航空気象":[],"解説":[]}; visible.filter(x=>x.local_path).forEach(x=>(groups[x.category]||(groups[x.category]=[])).push(x)); $("#charts").innerHTML=Object.entries(groups).map(([name,items])=>items.length?`<div class="chart-group"><h3>${esc(name)}</h3><div class="charts">${items.map(x=>`<article><div><span>${esc(x.abbreviation||x.category)}</span><a href="${esc(x.original_url)}" target="_blank">公式資料 ↗</a></div><h3>${esc(x.name)}</h3><img src="${base()}/${esc(x.local_path)}" alt="${esc(x.name)}"><small>取得 ${esc(x.fetched_at||"時刻不明")} · ${esc(x.status)}</small></article>`).join("")}</div></div>`:"").join("")||'<div class="empty panel">選択中の画像資料はありません。</div>';
  await renderData(visible); bindImages(); }
async function renderData(visible) { const byId=Object.fromEntries(visible.map(x=>[x.id,x]));
  const forecast=byId.forecast&&await loadData(byId.forecast); $("#forecast").innerHTML=forecast?`<h3>${esc(forecast.title)}</h3><p>${esc(forecast.headline)}</p><div class="forecast-days">${(forecast.forecasts||[]).map(day=>`<article><span>${esc(day.dateLabel||day.date)}</span>${day.image?.url?`<img src="${esc(day.image.url)}" alt="">`:""}<b>${esc(day.telop)}</b><small>${esc(day.temperature?.min?.celsius??"-")} / ${esc(day.temperature?.max?.celsius??"-")} ℃</small></article>`).join("")}</div>`:"保存済み予報はありません。";
  const amedas=byId.amedas&&await loadData(byId.amedas); $("#amedas").innerHTML=amedas?`<p>${esc(amedas.measurement_note||"")}</p><div class="metrics"><article><span>観測地点</span><strong>${amedas.rows?.length||0}</strong></article><article><span>最大1時間降水量</span><strong>${Math.max(0,...(amedas.rows||[]).map(x=>x.rain_1h||0))} mm</strong></article></div><div class="table"><table><thead><tr><th>地点</th><th>1時間降水量</th><th>日最高気温</th><th>最大風速</th></tr></thead><tbody>${(amedas.rows||[]).map(x=>`<tr><td>${esc(x.place)}</td><td>${esc(x.rain_1h??"-")} mm</td><td>${esc(x.temperature_max_c??"-")} ℃</td><td>${esc(x.wind_speed_max_m_s??"-")} m/s</td></tr>`).join("")}</tbody></table></div>`:"保存済み観測はありません。"; renderMap(amedas?.rows||[]);
  const commentary=[]; for (const id of ["past-observation-text"]) if(byId[id]) { const data=await loadData(byId[id]); commentary.push(`<details><summary>${esc(data.title||byId[id].name)}</summary><pre>${esc(data.text||"")}</pre></details>`); } $("#commentary").innerHTML=commentary.join("")||'<div class="empty panel">保存済みテキスト解説はありません。</div>';
  try { if(manifest.llm?.status!=="success") throw new Error("not generated"); const llm=await text(`${base()}/llm-analysis.md`); $("#llm").classList.remove("empty"); $("#llm").innerHTML=markdown(llm); } catch { $("#llm").classList.add("empty"); $("#llm").textContent=manifest.llm?.error?.message||"解説は生成されていません。"; }
}
function renderMap(rows) { const canvas=$("#station-map"); const points=rows.filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)); if(stationMap){stationMap.remove();stationMap=null;} if(!window.L||!points.length){canvas.hidden=true;return;} canvas.hidden=false; stationMap=L.map(canvas,{scrollWheelZoom:false}); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(stationMap); const marks=points.map(x=>L.circleMarker([x.lat,x.lon],{radius:6,color:"#fff",fillColor:"#ed6a4d",fillOpacity:1}).bindPopup(`${esc(x.place)}<br>降水 ${esc(x.rain_1h??"-")} mm`)); marks.forEach(x=>x.addTo(stationMap)); stationMap.fitBounds(L.featureGroup(marks).getBounds().pad(.15)); setTimeout(()=>stationMap.invalidateSize(),0); }
function bindImages() { document.querySelectorAll(".charts img").forEach(img=>img.onclick=()=>{$("#modal-image").src=img.src;$("#modal-image").alt=img.alt;$("#modal-caption").textContent=img.alt;$("#modal").showModal();}); }
function renderCatalog(){ $("#catalog").innerHTML=index.sources.map(x=>`<article><span>${esc(x.category)}</span><h3>${esc(x.name)}</h3><p>${esc(x.abbreviation||"公式資料")}</p><a href="${esc(x.view)}" target="_blank">公式資料 ↗</a></article>`).join(""); }
function renderGlossary(){ const glossary=index.glossary||{}; $("#reading-guides").innerHTML=(glossary.reading_guides||[]).map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join(""); $("#abbreviations").innerHTML=(glossary.abbreviations||[]).map(x=>`<article><code>${esc(x.code)}</code><div><h3>${esc(x.name)}</h3><p>${esc(x.meaning)}</p></div></article>`).join(""); }
document.addEventListener("change",e=>{if(e.target.matches("#filters input")){e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();}}); $("#select-all").onclick=()=>{selected=new Set(manifest.sources.map(x=>x.id));renderFilters();render();}; $("#select-none").onclick=()=>{selected.clear();renderFilters();render();}; $("#date").onchange=()=>{updateLocations();loadSnapshot();}; $("#location").onchange=loadSnapshot; $("#close").onclick=()=>$("#modal").close(); $("#modal-image").onclick=e=>e.currentTarget.classList.toggle("zoomed");
(async()=>{try{index=await json("index.json");$("#snapshot-count").textContent=index.snapshots.length;initializeSelectors();renderCatalog();renderGlossary();await loadSnapshot();}catch(error){$("#status").classList.add("error");$("#status").textContent=`読み込み失敗: ${error.message}。file:// ではなくHTTPサーバーで開いてください。`;}})();
