"use strict";
const WEATHER_TRIGGER_URL = "https://weather-study-trigger.lvtm-pal.workers.dev";
const ACTIVE_RUN_STORAGE_KEY = "weather_study_active_run_v1";
const ACTIONS_POLL_INTERVAL_MS = 5000;
const $ = selector => document.querySelector(selector);
const esc = value => String(value ?? "").replace(/[&<>"']/g, c => ({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let index, manifest, selected = new Set(), stationMap, activeRun = null, actionsDispatchPending = false, actionsPollTimer = null, actionsPollInFlight = false;
const sourceMap = () => Object.fromEntries(index.sources.map(source => [source.id, source]));
const available = () => index.snapshots.filter(item => (!$("#date").value || item.date === $("#date").value) && (!$("#location").value || item.location.id === $("#location").value));
const option = (value, label) => `<option value="${esc(value)}">${esc(label)}</option>`;
function markdown(text) { return esc(text).replace(/^### (.+)$/gm,"<h3>$1</h3>").replace(/^## (.+)$/gm,"<h2>$1</h2>").replace(/^# (.+)$/gm,"<h2>$1</h2>").replace(/\*\*(.+?)\*\*/g,"<strong>$1</strong>").replace(/^[-*] (.+)$/gm,"<li>$1</li>").replace(/(?:<li>.*<\/li>\n?)+/g,x=>`<ul>${x}</ul>`).replace(/\n{2,}/g,"</p><p>").replace(/^/,"<p>").replace(/$/,"</p>"); }
async function json(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.json(); }
async function text(path) { const response = await fetch(path); if (!response.ok) throw new Error(`${response.status} ${response.statusText}`); return response.text(); }
function syncQuery() { const query = new URLSearchParams({date:$("#date").value, location:$("#location").value}); history.replaceState(null,"",`?${query}`); }
function initializeSelectors() { const query = new URLSearchParams(location.search); const dates = [...new Set(index.snapshots.map(x=>x.date))].sort().reverse(); $("#date").innerHTML = dates.map(x=>option(x,x)).join(""); $("#date").value = dates.includes(query.get("date")) ? query.get("date") : dates[0] || ""; updateLocations(query.get("location")); }
function updateLocations(preferred) { const items = index.snapshots.filter(x=>x.date === $("#date").value); $("#location").innerHTML = items.map(x=>option(x.location.id,`${x.location.prefecture} — ${x.location.city}`)).join(""); if (items.some(x=>x.location.id===preferred)) $("#location").value=preferred; }
async function loadSnapshot() { const item = available()[0]; if (!item) { $("#status").textContent="この組み合わせのsnapshotはありません。"; return; } syncQuery(); manifest=await json(item.manifest); selected=new Set(manifest.sources.map(x=>x.id)); renderFilters(); await render(); }
function renderFilters() { const defs=sourceMap(); $("#filters").innerHTML=manifest.sources.map(item=>`<label><input type="checkbox" value="${esc(item.id)}" ${selected.has(item.id)?"checked":""}><span><b>${esc(defs[item.id]?.name||item.name)}</b><small>${esc(defs[item.id]?.category||item.category)} · ${esc(item.status)}</small></span></label>`).join(""); }
async function loadData(entry) { return entry.data_path ? json(`${base()}/${entry.data_path}`) : null; }
function base() { return `snapshots/${manifest.target_date}/${manifest.location.id}`; }
async function render() { const visible=manifest.sources.filter(x=>selected.has(x.id)); $("#snapshot-title").textContent=`${manifest.target_date} · ${manifest.location.prefecture} ${manifest.location.city}`; $("#generated-at").textContent=`生成 ${manifest.generated_at||"—"}`; $("#status").textContent=`${visible.length} / ${manifest.sources.length} 資料を表示中`; const latitude=manifest.location.latitude,longitude=manifest.location.longitude; $("#windy").href=`https://www.windy.com/${latitude}/${longitude}`; $("#windy-embed").src=`https://embed.windy.com/embed2.html?lat=${latitude}&lon=${longitude}&detailLat=${latitude}&detailLon=${longitude}&width=650&height=650&zoom=7&level=surface&overlay=rain&product=ecmwf&menu=&message=true`;
  const failures=visible.filter(x=>!["success","cached"].includes(x.status)); $("#errors").innerHTML=failures.map(x=>`<div class="error"><b>${esc(x.name)}</b>：${esc(x.error?.message||x.status)}</div>`).join("");
  const groups={"地上":[],"高層":[],"数値予報":[],"航空気象":[],"解説":[]}; visible.filter(x=>x.local_path).forEach(x=>(groups[x.category]||(groups[x.category]=[])).push(x)); $("#charts").innerHTML=Object.entries(groups).map(([name,items])=>items.length?`<div class="chart-group"><h3>${esc(name)}</h3><div class="charts">${items.map(x=>`<article><div><span>${esc(x.abbreviation||x.category)}</span><a href="${esc(x.original_url)}" target="_blank">公式資料 ↗</a></div><h3>${esc(x.name)}</h3><img src="${base()}/${esc(x.local_path)}" alt="${esc(x.name)}"><small>取得 ${esc(x.fetched_at||"時刻不明")} · ${esc(x.status)}</small></article>`).join("")}</div></div>`:"").join("")||'<div class="empty panel">選択中の画像資料はありません。</div>';
  await renderData(visible); bindImages(); }
async function renderData(visible) { const byId=Object.fromEntries(visible.map(x=>[x.id,x]));
  const forecast=byId.forecast&&await loadData(byId.forecast); $("#forecast").innerHTML=forecast?`<h3>${esc(forecast.title)}</h3><p>${esc(forecast.headline)}</p><div class="forecast-days">${(forecast.forecasts||[]).map(day=>`<article><span>${esc(day.dateLabel||day.date)}</span>${day.image?.url?`<img src="${esc(day.image.url)}" alt="">`:""}<b>${esc(day.telop)}</b><small>${esc(day.temperature?.min?.celsius??"-")} / ${esc(day.temperature?.max?.celsius??"-")} ℃</small></article>`).join("")}</div>`:"保存済み予報はありません。";
  const amedas=byId.amedas&&await loadData(byId.amedas); $("#amedas").innerHTML=amedas?`<p>${esc(amedas.measurement_note||"")}</p><div class="metrics"><article><span>観測地点</span><strong>${amedas.rows?.length||0}</strong></article><article><span>最大1時間降水量</span><strong>${Math.max(0,...(amedas.rows||[]).map(x=>x.rain_1h||0))} mm</strong></article></div><div class="table"><table><thead><tr><th>地点</th><th>1時間降水量</th><th>日最高気温</th><th>最大風速</th></tr></thead><tbody>${(amedas.rows||[]).map(x=>`<tr><td>${esc(x.place)}</td><td>${esc(x.rain_1h??"-")} mm</td><td>${esc(x.temperature_max_c??"-")} ℃</td><td>${esc(x.wind_speed_max_m_s??"-")} m/s</td></tr>`).join("")}</tbody></table></div>`:"保存済み観測はありません。"; renderMap(amedas?.rows||[]);
  const commentary=[]; for (const id of ["past-observation-text"]) if(byId[id]) { const data=await loadData(byId[id]); commentary.push(`<details><summary>${esc(data.title||byId[id].name)}</summary><pre>${esc(data.text||"")}</pre></details>`); } $("#commentary").innerHTML=commentary.join("")||'<div class="empty panel">保存済みテキスト解説はありません。</div>';
  try { if(manifest.llm?.status!=="success") throw new Error("not generated"); const llm=await text(`${base()}/llm-analysis.md`); $("#llm").classList.remove("empty"); $("#llm").innerHTML=markdown(llm); } catch { $("#llm").classList.add("empty"); $("#llm").textContent=manifest.llm?.error?.message||"解説は生成されていません。"; }
}
function renderMap(rows) { const canvas=$("#station-map"); const points=rows.filter(x=>Number.isFinite(x.lat)&&Number.isFinite(x.lon)); if(stationMap){stationMap.remove();stationMap=null;} if(!window.L||!points.length){canvas.hidden=true;return;} canvas.hidden=false; stationMap=L.map(canvas,{scrollWheelZoom:false}); L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(stationMap); const marks=points.map(x=>L.circleMarker([x.lat,x.lon],{radius:6,color:"#fff",fillColor:"#ed6a4d",fillOpacity:1}).bindPopup(`${esc(x.place)}<br>降水 ${esc(x.rain_1h??"-")} mm`)); marks.forEach(x=>x.addTo(stationMap)); stationMap.fitBounds(L.featureGroup(marks).getBounds().pad(.15)); setTimeout(()=>stationMap.invalidateSize(),0); }
function bindImages() { document.querySelectorAll(".charts img").forEach(img=>img.onclick=()=>{$("#modal-image").src=img.src;$("#modal-image").alt=img.alt;$("#modal-caption").textContent=img.alt;$("#modal").showModal();}); }
function renderCatalog(){ $("#catalog").innerHTML=index.sources.map(x=>`<article><span>${esc(x.category)}</span><h3>${esc(x.name)}</h3><p>${esc(x.abbreviation||"公式資料")}</p><a href="${esc(x.view)}" target="_blank">公式資料 ↗</a></article>`).join(""); }
function renderGlossary(){ const glossary=index.glossary||{}; $("#reading-guides").innerHTML=(glossary.reading_guides||[]).map(x=>`<article><h3>${esc(x.title)}</h3><p>${esc(x.body)}</p></article>`).join(""); $("#abbreviations").innerHTML=(glossary.abbreviations||[]).map(x=>`<article><code>${esc(x.code)}</code><div><h3>${esc(x.name)}</h3><p>${esc(x.meaning)}</p></div></article>`).join(""); }
function renderArchiveHistory(){ const entries=index.archive||[]; $("#archive-history").innerHTML=entries.length?entries.map(item=>{const place=item.location||{};const mode=item.collection_mode==="scheduled"?"自動取得":"手動取得";const gemini=item.llm_analysis?"Gemini解説あり":"Gemini解説なし";const query=new URLSearchParams({date:item.date,location:place.id||"tokyo"});return `<a href="?${query}" class="archive-row"><time>${esc(item.date)}</time><span><b>${esc(place.prefecture||"")} ${esc(place.city||place.id||"")}</b><small>${esc(item.source_count??item.sources?.length??0)}資料</small></span><span class="archive-badges"><i class="mode-${esc(item.collection_mode||"manual")}">${mode}</i><i class="${item.llm_analysis?"has-llm":""}">${gemini}</i></span></a>`;}).join(""):'<div class="empty panel">取得履歴はまだありません。</div>'; }
function jstToday(){ const parts=new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Tokyo",year:"numeric",month:"2-digit",day:"2-digit"}).formatToParts(new Date()); const values=Object.fromEntries(parts.map(part=>[part.type,part.value])); return `${values.year}-${values.month}-${values.day}`; }
function safeActionsUrl(value){ try { const url=new URL(value); return url.protocol==="https:"&&url.hostname==="github.com" ? url.href : ""; } catch { return ""; } }
function setTriggerStatus(message,type=""){ const target=$("#snapshot-trigger-status"); target.textContent=message; target.className=`trigger-status ${type}`.trim(); }
function setTriggerBusy(busy){ $("#snapshot-trigger-button").disabled=busy; $("#snapshot-request-date").disabled=busy; $("#snapshot-request-location").disabled=busy; $("#snapshot-request-sources").disabled=busy; $("#snapshot-request-force").disabled=busy; }
function showActionsLink(value){ const link=$("#snapshot-trigger-link"); const safe=safeActionsUrl(value); link.hidden=!safe; if(safe) link.href=safe; }
function saveActiveRun(){ try { localStorage.setItem(ACTIVE_RUN_STORAGE_KEY,JSON.stringify(activeRun)); return true; } catch { return false; } }
function clearActiveRun(){ activeRun=null; try { localStorage.removeItem(ACTIVE_RUN_STORAGE_KEY); } catch {} if(actionsPollTimer) clearTimeout(actionsPollTimer); actionsPollTimer=null; actionsPollInFlight=false; }
async function workerResponse(response){ let payload; try { payload=await response.json(); } catch { throw new Error(`WorkerからJSONを取得できませんでした（HTTP ${response.status}）`); } if(!response.ok||payload.ok===false) throw new Error(payload.error||`Worker request failed（HTTP ${response.status}）`); return payload; }
function requestedSources(){ const mode=$("#snapshot-request-sources").value; if(mode!=="selected") return mode; const ids=[...selected]; if(!ids.length) throw new Error("現在チェックしている資料が0件です。資料を選択してから実行してください。"); return ids.join(","); }
function initializeSnapshotTrigger(){ const locationSelect=$("#snapshot-request-location"); locationSelect.innerHTML=index.locations.map(item=>option(item.id,`${item.prefecture} — ${item.city}`)).join(""); const current=$("#location").value||new URLSearchParams(location.search).get("location")||"tokyo"; locationSelect.value=index.locations.some(item=>item.id===current)?current:"tokyo"; $("#snapshot-request-date").value=jstToday(); $("#snapshot-trigger-button").onclick=startSnapshotUpdate; }
async function startSnapshotUpdate(){ if(activeRun||actionsDispatchPending) return; actionsDispatchPending=true; let payload; try { payload={date:$("#snapshot-request-date").value,location:$("#snapshot-request-location").value,sources:requestedSources(),force:$("#snapshot-request-force").checked}; if(!/^\d{4}-\d{2}-\d{2}$/.test(payload.date)) throw new Error("対象日を選択してください。"); if(!payload.location) throw new Error("地点を選択してください。"); setTriggerBusy(true); showActionsLink(""); setTriggerStatus("GitHub Actionsを開始しています…","running"); const response=await fetch(WEATHER_TRIGGER_URL,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}); const result=await workerResponse(response); if(!result.run_id) throw new Error("Workerレスポンスにrun_idがありません。"); activeRun={run_id:result.run_id,html_url:safeActionsUrl(result.html_url),...payload,started_at:new Date().toISOString()}; actionsDispatchPending=false; saveActiveRun(); showActionsLink(activeRun.html_url); setTriggerStatus("GitHub Actionsの実行待ちです…","running"); scheduleActionsPoll(0); } catch(error){ actionsDispatchPending=false; clearActiveRun(); setTriggerBusy(false); setTriggerStatus(`更新を開始できませんでした：${error.message}`,"error"); } }
function scheduleActionsPoll(delay=ACTIONS_POLL_INTERVAL_MS){ if(actionsPollTimer) clearTimeout(actionsPollTimer); actionsPollTimer=setTimeout(checkActiveRunStatus,delay); }
async function checkActiveRunStatus(){ if(!activeRun||actionsPollInFlight) return; actionsPollInFlight=true; try { const response=await fetch(`${WEATHER_TRIGGER_URL}/status?run_id=${encodeURIComponent(activeRun.run_id)}`); const result=await workerResponse(response); if(result.html_url){ activeRun.html_url=safeActionsUrl(result.html_url)||activeRun.html_url; saveActiveRun(); } showActionsLink(activeRun.html_url); if(result.status==="completed"){ if(result.conclusion==="success"){ const completed={...activeRun}; clearActiveRun(); setTriggerBusy(true); setTriggerStatus("更新完了。最新ページを読み込みます…","success"); const next=new URL(location.href); next.search=new URLSearchParams({date:completed.date,location:completed.location}).toString(); setTimeout(()=>location.assign(next.href),1200); return; } const conclusion=result.conclusion||"unknown"; clearActiveRun(); setTriggerBusy(false); setTriggerStatus(`更新に失敗しました（${conclusion}）。GitHub Actionsのログを確認してください。`,"error"); return; } if(result.status==="queued") setTriggerStatus("GitHub Actionsの実行待ちです…","running"); else if(result.status==="in_progress") setTriggerStatus("気象資料を取得し、ページを生成中です…","running"); else setTriggerStatus(`GitHub Actionsの状態を確認中です（${result.status||"unknown"}）…`,"running"); scheduleActionsPoll(); } catch(error){ setTriggerStatus(`状態確認に失敗しました。再試行します…（${error.message}）`,"error"); scheduleActionsPoll(ACTIONS_POLL_INTERVAL_MS); } finally { actionsPollInFlight=false; } }
function restoreActiveRun(){ let saved; try { saved=JSON.parse(localStorage.getItem(ACTIVE_RUN_STORAGE_KEY)||"null"); } catch { try { localStorage.removeItem(ACTIVE_RUN_STORAGE_KEY); } catch {} } if(!saved||!(typeof saved.run_id==="number"||typeof saved.run_id==="string")) return; activeRun={run_id:saved.run_id,html_url:safeActionsUrl(saved.html_url),date:saved.date,location:saved.location,sources:saved.sources,force:Boolean(saved.force),started_at:saved.started_at}; setTriggerBusy(true); showActionsLink(activeRun.html_url); setTriggerStatus("保存されていたGitHub Actionsの状態を確認しています…","running"); scheduleActionsPoll(0); }
document.addEventListener("change",e=>{if(e.target.matches("#filters input")){e.target.checked?selected.add(e.target.value):selected.delete(e.target.value);render();}}); $("#select-all").onclick=()=>{selected=new Set(manifest.sources.map(x=>x.id));renderFilters();render();}; $("#select-none").onclick=()=>{selected.clear();renderFilters();render();}; $("#date").onchange=()=>{updateLocations();loadSnapshot();}; $("#location").onchange=loadSnapshot; $("#close").onclick=()=>$("#modal").close(); $("#modal-image").onclick=e=>e.currentTarget.classList.toggle("zoomed"); $("#toggle-windy").onclick=event=>{const frame=$(".windy-frame");const enabled=frame.classList.toggle("interactive");event.currentTarget.textContent=enabled?"Windyの操作を終了":"Windyを操作する";};
(async()=>{try{index=await json("index.json");$("#snapshot-count").textContent=index.snapshots.length;initializeSelectors();renderCatalog();renderGlossary();renderArchiveHistory();await loadSnapshot();initializeSnapshotTrigger();restoreActiveRun();}catch(error){$("#status").classList.add("error");$("#status").textContent=`読み込み失敗: ${error.message}。file:// ではなくHTTPサーバーで開いてください。`;}})();
